# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0bed8ab98d0ef5358ff64fdf665d7428"
application_url = "https://sevsync.saurer-siggi.de"
embedded = true
name = "sevdesk-sync"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_all_orders,read_customers"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = [ "orders/paid" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/cancelled"
  topics = [ "orders/cancelled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/refunds/create"
  topics = [ "refunds/create" ]

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

[auth]
redirect_urls = [ "https://sevsync.saurer-siggi.de/api/auth" ]

[build]
automatically_update_urls_on_dev = true
